source "http://rubygems.org"

gem "rack", "1.3.5"
gem "sinatra", "1.3.1"
gem "mongo_mapper"
gem "haml"
gem "sass"
gem "json"
gem "shotgun"
gem "pony"
gem "ruby-gmail"
gem "omniauth"
gem "omniauth-facebook"
gem "bson_ext"
gem "i18n"
gem "mime"
gem "emk-sinatra-url-for"
gem "loofah"
gem "htmlentities"
gem "redis"
gem "feedzirra"
gem "diffbot"
